# Site settings
title: The Invention of Photography in the Victorian World
subtitle:
author: Jennifer Green‑Lewis
description: "A rich exploration of Victoria's portrayal in photography and her role in shaping the medium"
permalink: none # this removes the required date (YYYY-MM-DD) from the post URLs

baseurl: "/inventionofphoto-jekyll" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
